export const clientProjectData = [
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "ACTIVE",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "CLOSE",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
    {
        projectId: 1,
        title: "프로젝트 제목",
        payment: 1000000,
        applicantsCount: 5,
        estimatedDays: 30,
        applicationDuration: {
            startDate: "2024-07-01",
            endDate: "2024-07-31",
        },
        hashtags: ["#해시태그1", "#해시태그2"],
        description: "프로젝트 설명",
        status: "APPLYING",
    },
];
