name: (get-p-client) Run Unit, Integration Tests

concurrency:
    group: get-p-client
    cancel-in-progress: true

on:
    workflow_dispatch:

    pull_request:
        branches:
            - develop

    workflow_run:
        workflows: ["Setup Runner Instance", (get-p-client) Compile & Linting]
        types: completed

jobs:
    unit-test:
        runs-on: self-hosted

        steps:
            - name: Run Tests
              run: yarn client test
