name: (get-p-design) Build

concurrency:
    group: get-p-frontend
    cancel-in-progress: true

on:
    workflow_dispatch:

    workflow_run:
        workflows: ["(get-p-design) Run Tests"]
        types: completed

    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Build Design System
              run: yarn design build
