name: (get-p-client) Run Tests

on:
    workflow_dispatch:

    pull_request:
        branches:
            - develop

jobs:
    check-env:
        runs-on: self-hosted

        steps:
            - name: Check Node Version
              working-directory: ~/get-p-frontend
              run: |
                  if [[ "$(node --version)" != v20* ]]; then
                    echo "Node.js major version should be 20"
                    exit 1
                  fi

    setup:
        runs-on: self-hosted

        steps:
            - name: Update Source Code
              working-directory: ~/get-p-frontend
              run: |
                  git reset --hard
                  git clean -fd
                  git pull origin main

            - name: Checkout Specific Branch
              working-directory: ~/get-p-frontend
              run: |
                  git fetch origin
                  git checkout ${{ github.ref_name }}
                  git pull origin ${{ github.ref_name }}

            - name: Install Dependencies
              working-directory: ~/get-p-frontend
              run: |
                  yarn install --frozen-lockfile

    compile-and-lint:
        needs: [check-env, setup]
        runs-on: self-hosted

        steps:
            - name: Run Compile and Lint
              working-directory: ~/get-p-frontend
              run: |
                  yarn client compile
                  yarn client lint

    unit-test:
        needs: [compile-and-lint]
        runs-on: self-hosted

        steps:
            - name: Run Unit Test
              working-directory: ~/get-p-frontend
              run: |
                  yarn client test

    setup-e2e-test:
        needs: [unit-test]
        runs-on: self-hosted

        steps:
            - name: Setup e2e Test Server
              working-directory: ~/get-p-server
              run: git clone https://github.com/Principes-Artis-Mechanicae/get-p-server.git
