name: (get-p-client) Deploy On Production Server

on:
    pull_request:
        branches:
            - main
        types:
            - closed

    workflow_dispatch:

env:
    DOCKER_IMAGE_TAG: ${{secrets.DOCKER_USERNAME}}/get-p-frontend:latest

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Set Up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build and Push to DockerHub
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{env.DOCKER_IMAGE_TAG}}

    deploy:
        runs-on: self-hosted
        needs: build

        steps:
            - name: Stop Running Container and Remove Images
              run: |
                  sudo docker stop get-p-frontend || true
                  sudo docker rm get-p-frontend || true
                  sudo docker rmi ${{env.DOCKER_IMAGE_TAG}} || true

            - name: Pull Docker Image from Dockerhub
              run: sudo docker pull ${{env.DOCKER_IMAGE_TAG}}

            - name: Run Container
              run: sudo docker run -d -p ${{secrets.FORWARDING_PORT}} --name get-p-frontend ${{env.DOCKER_IMAGE_TAG}}

            - name: Prune Unused Containers and Images
              run: sudo docker system prune -a -f
