name: (get-p-client) Deploy Storybook

on:
    pull_request:
        branches: [develop]
        types: [closed]
    workflow_dispatch:

jobs:
    storybook:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Change Directory to get-p-client
              run: cd get-p-client

            - name: Deploy Storybook
              uses: chromaui/action@v11
              with:
                  projectToken: ${{ secrets.STORYBOOK_TOKEN }}
