name: (get-p-client) Run e2e Test

on:
    workflow_dispatch:

    pull_request:
        branches: ["main", "release"]

    workflow_run:
        workflows: ["(get-p-client) Compile & Linting", "(get-p-client) Run Unit, Integration Tests"]
        types: completed

jobs:
    setup-e2e:
        runs-on: self-hosted

        steps:
            - name: Checkout Backend Code
              uses: actions/checkout@v4
              with:
                  repository: get-p/get-p-backend
                  ref: develop

    e2e:
        runs-on: self-hosted

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Yarn Package Manager
              run: npm install -g yarn

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Build get-p-design system
              run: yarn design build

            - name: Change Directory to get-p-client
              run: cd get-p-client

            - name: Setup Environment Variables
              run: |
                  touch .env
                  echo VITE_API_BASE_URL=${{secrets.VITE_API_BASE_URL}} >> .env
                  cd ..

            - name: Build
              run: yarn client build

            - name: Run e2e Tests
              run: yarn client test:e2e:ci
