name: (get-p-client) Compile & Linting

concurrency:
    group: (get-p-client) Test
    cancel-in-progress: true

on:
    workflow_dispatch:

    pull_request:
        branches:
            - develop

jobs:
    compile_and_lint:
        runs-on: self-hosted

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install Yarn Package Manager
              run: npm install -g yarn

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Build get-p-design system
              run: yarn design build

            - name: Typescript Compile
              run: yarn client compile

            - name: Lint Code
              run: yarn client lint
