name: Deploy on Beta Server (Netlify)

on:
    pull_request:
        branches: [develop]
        types: [closed]

jobs:
    storybook:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - run: yarn

            - uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.STORYBOOK_TOKEN }}
