name: Deploy Storybook

on:
    pull_request:
        branches: [develop]
        types: [closed]

jobs:
    storybook:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: yarn

            - uses: chromaui/action@v11
              with:
                  projectToken: ${{ secrets.STORYBOOK_TOKEN }}
