name: Run e2e Test

on:
    pull_request:
        branches: ["main", "develop", "release"]
    workflow_dispatch:

jobs:
    e2e:
        runs-on: ubuntu-latest

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v4

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm ci

            - name: Setup Environment Variables
              run: |
                  touch .env
                  echo VITE_API_BASE_URL=${{secrets.VITE_API_BASE_URL}} >> .env

            - name: Build
              run: npm run build

            - name: Run e2e Tests
              run: npm run test:e2e-ci
